# Generated by Django 5.0.7 on 2024-07-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='body',
        ),
        migrations.AddField(
            model_name='todo',
            name='complited',
            field=models.BooleanField(default=False),
        ),
    ]
